# Generated by Django 4.2.6 on 2023-10-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField(unique=True)),
                ("current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-season"],
            },
        ),
    ]
