# Generated by Django 4.2.6 on 2023-10-10 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nhl", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Franchise",
            fields=[
                (
                    "franchise_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("timezone_id", models.CharField(max_length=100)),
                ("timezone_offset", models.IntegerField()),
                ("timezone_tz", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=10)),
                ("team_name", models.CharField(max_length=100)),
                ("location_name", models.CharField(max_length=100)),
                ("first_year_of_play", models.CharField(max_length=4)),
                ("roster", models.JSONField()),
                ("short_name", models.CharField(max_length=100)),
                ("official_site_url", models.URLField()),
                ("active", models.BooleanField()),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nhl.conference"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nhl.division"
                    ),
                ),
                (
                    "franchise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nhl.franchise"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nhl.season"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nhl.venue"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.IntegerField(unique=True)),
                ("link", models.URLField()),
                ("game_type", models.CharField(max_length=1)),
                ("game_date", models.DateTimeField()),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_team",
                        to="nhl.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_team",
                        to="nhl.team",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nhl.season"
                    ),
                ),
            ],
            options={
                "ordering": ["-game_date"],
            },
        ),
    ]
