# Generated by Django 4.2.6 on 2023-10-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nhl", "0002_conference_division_franchise_venue_team_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="live",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("id", "season")},
        ),
    ]
