# Generated by Django 4.2.6 on 2023-10-10 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nhl", "0003_game_completed_game_live_alter_team_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Freq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("away_days_rest", models.IntegerField()),
                (
                    "away_pst_2_mst_b2b",
                    models.BooleanField(db_column="amstb2b", default=False),
                ),
                (
                    "away_first_of_2",
                    models.BooleanField(db_column="a1of2", default=False),
                ),
                (
                    "away_first_of_3",
                    models.BooleanField(db_column="a1of3", default=False),
                ),
                ("away_2_of_3", models.BooleanField(db_column="a2of3", default=False)),
                ("away_b2b", models.BooleanField(db_column="ab2b", default=False)),
                ("away_b2b2b", models.BooleanField(db_column="ab2b2b", default=False)),
                (
                    "away_two_in_three",
                    models.BooleanField(db_column="a2n3", default=False),
                ),
                (
                    "away_three_in_four",
                    models.BooleanField(db_column="a3n4", default=False),
                ),
                (
                    "away_four_in_five",
                    models.BooleanField(db_column="a4n5", default=False),
                ),
                (
                    "away_four_in_six",
                    models.BooleanField(db_column="a4n6", default=False),
                ),
                (
                    "away_five_in_six",
                    models.BooleanField(db_column="a5n6", default=False),
                ),
                (
                    "away_five_in_seven",
                    models.BooleanField(db_column="a5n7", default=False),
                ),
                (
                    "away_six_in_eight",
                    models.BooleanField(db_column="a6n8", default=False),
                ),
                (
                    "away_six_in_nine",
                    models.BooleanField(db_column="a6n9", default=False),
                ),
                (
                    "away_seven_in_nine",
                    models.BooleanField(db_column="a7n9", default=False),
                ),
                (
                    "away_seven_in_ten",
                    models.BooleanField(db_column="a7n10", default=False),
                ),
                (
                    "away_seven_in_eleven",
                    models.BooleanField(db_column="a7n11", default=False),
                ),
                (
                    "away_eight_in_eleven",
                    models.BooleanField(db_column="a8n11", default=False),
                ),
                (
                    "away_nine_in_twelve",
                    models.BooleanField(db_column="a9n12", default=False),
                ),
                ("home_days_rest", models.IntegerField()),
                (
                    "home_pst_2_mst_b2b",
                    models.BooleanField(db_column="hmstb2b", default=False),
                ),
                (
                    "home_first_of_2",
                    models.BooleanField(db_column="h1of2", default=False),
                ),
                (
                    "home_first_of_3",
                    models.BooleanField(db_column="h1of3", default=False),
                ),
                ("home_2_of_3", models.BooleanField(db_column="h2of3", default=False)),
                ("home_b2b", models.BooleanField(db_column="hb2b", default=False)),
                ("home_b2b2b", models.BooleanField(db_column="hb2b2b", default=False)),
                (
                    "home_two_in_three",
                    models.BooleanField(db_column="h2n3", default=False),
                ),
                (
                    "home_three_in_four",
                    models.BooleanField(db_column="h3n4", default=False),
                ),
                (
                    "home_four_in_five",
                    models.BooleanField(db_column="h4n5", default=False),
                ),
                (
                    "home_four_in_six",
                    models.BooleanField(db_column="h4n6", default=False),
                ),
                (
                    "home_five_in_six",
                    models.BooleanField(db_column="h5n6", default=False),
                ),
                (
                    "home_five_in_seven",
                    models.BooleanField(db_column="h5n7", default=False),
                ),
                (
                    "home_six_in_eight",
                    models.BooleanField(db_column="h6n8", default=False),
                ),
                (
                    "home_six_in_nine",
                    models.BooleanField(db_column="h6n9", default=False),
                ),
                (
                    "home_seven_in_nine",
                    models.BooleanField(db_column="h7n9", default=False),
                ),
                (
                    "home_seven_in_ten",
                    models.BooleanField(db_column="h7n10", default=False),
                ),
                (
                    "home_seven_in_eleven",
                    models.BooleanField(db_column="h7n11", default=False),
                ),
                (
                    "home_eight_in_eleven",
                    models.BooleanField(db_column="h8n11", default=False),
                ),
                (
                    "home_nine_in_twelve",
                    models.BooleanField(db_column="h9n12", default=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="away_altitude_difference",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="away_days_rest",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="away_distance_travelled",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="home_altitude_difference",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="home_days_rest",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="home_distance_travelled",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="previous_away_game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_away_game",
                to="nhl.game",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="previous_home_game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_home_game",
                to="nhl.game",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="venue",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="nhl.venue"
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="game",
            name="freq",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="nhl.freq"
            ),
        ),
    ]
